### ISSUE TITLE
Mobile required field validation

### ISSUE THREAD

**Issue by bwilhelm** [nzjs/mailchimp-3.0-php-signup#2]
Hi - thanks for this code. Very nice implementation. I did find that on a mobile browser, the validation of the required field doesn't work. The user can submit a blank form it appears. I did modify the form and add more fields, but it works fine on a desktop. I'm wondering if you might have insight as to why it wouldn't work on mobile Safari, for example.

**Comment by nzjs** [comment]
I believe this is actually an issue with mobile Safari not supporting the HTML5 "required" attribute. 

This might be a solution for you: http://stackoverflow.com/a/31319587
